config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :carts do
    resources :orders
    get '/checkout', to: 'pages#checkout', as: :checkout
  end
  resources :products do
    resources :carpros, only: [:create]
  end
  resources :carpros, only: [:destroy]

  root to: 'products#index'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carpro.rb
class Carpro < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :products
  has_many :carpros, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :address, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
  validates :zipcode, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :emoney_number, presence: true
  validates :emoney_pin, presence: true
end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :pieces, dependent: :destroy
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :nav_categories

  def nav_categories
    @categories = Category.all
  end
end

app/controllers/carpros_controller.rb
class CarprosController < ApplicationController

  def create_cart
    @cart = Cart.new
    @cart.user = current_user
    @cart.save
    @cart
  end

  def create_carpro(product, cart)
    @carpro = Carpro.new(carpro_params)
    @carpro.product = product
    @carpro.cart = cart
    @carpro.save
    redirect_to cart_path(cart)
  end

  def create
    @product = Product.find(params[:product_id])
    @carts = current_user.carts

    if @carts.empty?
      @cart = create_cart
      create_carpro(@product, @cart)
    end

    if @carts.last.orders.empty? || @carts.last.orders.last.confirmed == false
      create_carpro(@product, current_user.carts.last)
    else
      @cart = create_cart
      create_carpro(@product, @cart)
    end
  end

  def destroy
    @carpro = Carpro.find(params[:id])
    @carpro.destroy
    redirect_to cart_path(current_user)
  end

  def carpro_params
    params.require(:carpro).permit(:quantity, :product_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ApplicationHelper

  def show
    @categories = Category.all
    @user = current_user

    if @user.carts.empty?
      @cart = Cart.new
      @cart.save
    else
      @cart = @user.carts.last
      @carpros = @cart.carpros
      @sum = carpros_sum(@carpros)
    end
  end

  def create
  end

  def update
  end

  private

  def cart_params
    params.require(:cart).permit(:user)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @category = Category.find(params[:id])
    @products = Product.where(category: @category)
    @categories = Category.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @categories = Category.all
    @user = current_user
    @order = Order.find(params[:id])
    @last_cart = Cart.find(@order.cart_id)
    @order.confirmed = true
    if @order.save
      @cart = Cart.new
      @cart.user = @user
      @cart.save
    end
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @cart = params[:cart_id]
    @order.cart_id = @cart

    if @order.save
      redirect_to cart_order_path(@cart, @order)
    else
      flash.alert = "Fields can't be blank"
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :address, :email, :phone_number, :zipcode, :city, :country, :emoney_number, :emoney_pin)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  include ApplicationHelper

  def home
  end

  def checkout
    @categories = Category.all
    @cart = current_user.carts.last
    @carpros = Carpro.where(cart: @cart)
    @order = Order.new
    @sum = carpros_sum(@carpros)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @products = Product.all
    @categories = Category.all
    @category = @categories.first
    @product = Product.find_by(category: @category.id)

    @zx7 = Product.find_by(name: "ZX7 Speaker")
    @zx9 = Product.find_by(name: "ZX9 Speaker")
    @yx1 = Product.find_by(name: "YX1 Wireless Earphones")
  end

  def show
    @products = Product.all.order('RANDOM()').limit(3)
    @categories = Category.all
    @product = Product.find(params[:id])
    @pieces = Piece.where(product: @product)
    @carpro = Carpro.new

    @image = @product.image
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def carpros_sum(carpros)
    sum = 0
    carpros.each do |carpro|
      sum += (carpro.quantity * carpro.product.price)
    end
    sum
  end
end

app/views/carts/_cart.html.erb
<div class="cart-box">
  <span> Summary </span>
  <ul>
  <% @carpros.each do |carpro| %>
  <li class="cart-item">
    <div class="cart-image" style="background-image: url('https://res.cloudinary.com/db7q8jblt/image/upload/v1639684182/audiophile<%= carpro.product.image %>')">
    </div>
    <div>
      <p class="cart-product-name"><%= carpro.product.name %></p>
      <p class="cart-product-price">$<%= carpro.product.price %> <span class="cart-quantity"> x<%= carpro.quantity %></span></p>
    </div>
    <div>
      <%= link_to "X",
      carpro_path(carpro),
      method: :delete  %>
    </div>
    </li>
    <% end %>
  </ul>

  <ul class="cart-totals">
    <li> Total: <span>$<%= @sum %></span> </li>
    <li> Shipping: <span>$50</span> </li>
    <li> VAT: <span>$<%= (@sum + 50) / 5 %></span> </li>
    <li class="grand-total"> Grand Total: <span>  <span>$<%= @sum + ((@sum + 50) / 5) %> </span> </li>
  </ul>
</div>

app/views/carts/show.html.erb
<section id="cart">

  <div class="cart-inner container">
  <% if @cart.carpros.empty? %>
  <h1> Your cart is empty... </h1>
  <% else %>
  <h1> Your cart </h1>
  <%= render "cart" %>

  <div class="proceed-checkout">
    <%=link_to "checkout", cart_checkout_path(@cart), class: "btn-audiophile"%>
  </div>

  <% end %>

  </div>

</section>

app/views/categories/show.html.erb
<section class="category">
  <div class="category-outer container">
        <h1><%= @category.name %></h1>

      <div class="category-inner">
        <div class="card-outer">
          <div class="card-inner">
            <% @products.each do |product|%>
            <%= render 'products/cardproduct', product: product %>
          <% end %>
          </div>
        </div>
      </div>

      <div>
        <%= render 'products/categories', categories: @categories %>
      </div>

      <div>
        <%= render 'products/bringing'%>
      </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Audiophile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar', categories: @categories unless params[:action] == "index" %>

    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/orders/show.html.erb
<section id="order">
  <div class="container order-inner">
    <div class="order-box">
     <h5> Thank You </h5>
    <ul>
      <p> You just bought:</p>
      <% @last_cart.carpros.each do |carpro|%>
      <li> <div class="order-image" style="background-image: url('https://res.cloudinary.com/db7q8jblt/image/upload/v1639684182/audiophile<%= carpro.product.image %>')"> </div> <%= carpro.product.name %> </li>
      <% end %>
    </ul>
    </div>
  </div>
</section>

app/views/pages/checkout.html.erb
<section id="checkout-cart">

  <div class="container">

  <div class="go-back">
   <%= link_to 'Go Back', products_path%>
  </div>

  <div class="checkout-cart-inner">

    <div class="checkout-module">

      <h1> Checkout </h1>

      <%= simple_form_for([@cart, @order]) do |f| %>
        <h4> Billing Details </h4>
        <div class="row">
          <%= f.input :name %>
          <%= f.input :email %>
        </div>
        <%= f.input :phone_number %>

        <h4> Shipping Info </h4>
        <%= f.input :address %>
        <div class="row">
          <%= f.input :zipcode %>
          <%= f.input :city %>
        </div>
        <%= f.input :country %>

        <h4> Payment Details </h4>
        <div class="row">
          <%= f.input :emoney_number %>
          <%= f.input :emoney_pin %>
        </div>
        <%= f.submit "Confirm", class: "btn-audiophile" %>
      <% end %>
    </div>

    <div class="cart-module">
      <%= render "carts/cart", sum: @sum %>
    </div>

  </div>
  </div>

</section>

app/views/pages/home.html.erb
<h1> </h1>

app/views/products/_bringing.html.erb
<section id="bringing">
  <div class="container">
    <div class="bringing-box">
      <div class="bringing-info">
      <h2> Bringing you the <span>best</span> audio gear </h2>
      <p> Located at the heart of New York City, Audiophile is the premier store for high end headphones,
  earphones, speakers, and audio accessories. We have a large showroom and luxury demonstration
  rooms available for you to browse and experience a wide range of our products. Stop by our store
  to meet some of the fantastic people who make Audiophile the best place to buy your portable
  audio equipment.</p>
      </div>
      <div class="bringing-image">
      </div>
    </div>
  </div>
</section>

app/views/products/_cardproduct.html.erb
<div class="card-box">
  <div style="background-image: url('https://res.cloudinary.com/db7q8jblt/image/upload/v1639684182/audiophile<%=product.image%>')"> </div>
  <h2> <%= product.name %> </h2>
  <%= link_to "See Product", product_path(product), class: "btn-audiophile btn-small" %>
</div>

app/views/products/_categories.html.erb
<section id="categories">

  <div class="container categories-outer">

    <div class="categories-inner">

      <% categories.each do |category| %>
      <div class="category-box">
      <%= link_to  category_path(category) do %>
        <div class="category-image" style="background-image: url('<%= category.image_url[0] %>')"> </div>
        <div class="category-info">
          <p><%= category.name %></p>
          <p class="shop"> Shop <%=cl_image_tag('audiophile/shared/desktop/icon-arrow-right_mzunen')%> </p>
          <% end %>
        </div>
      </div>
      <% end %>

    </div>


  </div>

</section>

app/views/products/_featured.html.erb
<section id="featured">
  <div class="container featured-inner">

    <div class="feature-box orange">
      <div class="image-side">
       <span class="circles"> <%= cl_image_tag('audiophile/home/desktop/pattern-circles_c5knqk') %> </span>
       <span class="speakers-image"><%= cl_image_tag('audiophile/home/desktop/image-speaker-zx9_wsgljg')%></span>
      </div>
      <div class-="info-side">
        <h3> <%= zx9.name %> </h3>
        <p> <%= zx9.description %> </p>
        <p><%= link_to "See Product", product_path(zx9), class: "btn-alt" %></p>
      </div>
    </div>

    <div class="feature-box unique" style="background-image: url('https://res.cloudinary.com/db7q8jblt/image/upload/v1639684181/audiophile/home/desktop/image-speaker-zx7_q3cwff.jpg') ">
      <div class-="info-side">
        <h3> <%= zx7.name %> </h3>
        <%= link_to "See Product", product_path(zx7), class: "btn-audiophile" %>
      </div>
    </div>

    <div class="split">
      <div class="image-side feature-box" style="background-image: url('https://res.cloudinary.com/db7q8jblt/image/upload/v1639684181/audiophile/home/desktop/image-earphones-yx1_hwuwpi.jpg')">

      </div>
      <div class="info-side feature-box">
        <h3> <%= yx1.name %> </h3>
        <%= link_to "See Product", product_path(yx1), class: "btn-audiophile" %>
      </div>
    </div>

  </div>
</section>

app/views/products/_hero.html.erb
<section id="hero">
  <div class="container">

  <div class="<%= params[:action] == "index" ? "bg-none" : "bg-black" %>">
    <%= render 'shared/navbar', categories: categories %>
  </div>

    <div class="hero-product">

      <div class="hero-product-info">
        <h3><%= product.new ? "New Product" : "Arrival" %></h3>
        <h1><%= product.name %></h1>
        <p><%= product.description %></p>
        <div id="button-area"><%= link_to "See Product", product_path(product), class: "btn-audiophile" %></div>
      </div>
      <div class="hero-product-image">
      </div>
    </div>
  </div>
</section>

app/views/products/index.html.erb
<%= render 'hero', product: @product, categories: @categories %>

<main class="bg-light">
<%= render 'categories', categories: @categories %>

<%= render 'featured', zx9: @zx9, zx7: @zx7, yx1: @yx1%>

<%= render 'bringing' %>

</main>

app/views/products/show.html.erb
<section class="product">

  <div class="container product-inner">

    <%= link_to 'Go Back', products_path %>

    <div class="row-1 product-row">
      <div class="product-image product-row-box" style="background-image: url('https://res.cloudinary.com/db7q8jblt/image/upload/v1639684182/audiophile<%= @image %>');">
      </div>
      <div class="product-info product-row-box">
        <h3><%= @product.new? ? "New Product" : "Arrival" %></h3>
        <h1><%= @product.name %></h1>
        <p class="product-description"><%= @product.description %></p>
        <p class="product-price">$<%= @product.price %></p>
        <div class="product-form">
          <%= simple_form_for([@product, @carpro]) do |f| %>
          <div class="row">
            <%= f.label "Quantity"%>
          </div>
           <div class="row">
            <%= f.number_field :quantity, min: "0", label: "Quantity", class: "btn-alt" %>
            <%= f.submit "Add To Cart", class: "btn-audiophile" %>
          </div>
           <% end %>
        </div>
        </div>
      </div>


      <div class="row-2 product-row">
        <div class="product-features product-row-box">
          <h2> Features </h2>
          <p> <%= @product.features %> </p>
        </div>
        <div class="product-pieces product-row-box">
          <div>
            <h2> In The Box </h2>
            <ul>
              <% @pieces.each do |piece| %>
              <li> <span class="piece-quantity"> <%= piece.quantity %>x </span><%= piece.name %>  </li>
              <% end %>
          </ul>
            </div>
        </div>
      </div>

      <div class="row-3 product-row">
        <div class="gallery">
          <% @product.galery_array.each do |image|%>
            <div class="product-row-grid" style="background-image: url('https://res.cloudinary.com/db7q8jblt/image/upload/v1639684182/audiophile<%= image %>">
             </div>
          <% end %>
        </div>
      </div>

      <div class="row-4 product-row">
        <div class="card-outer">
          <div class="card-inner">
            <% @products.each do |product|%>
            <%= render 'cardproduct', product: product %>
          <% end %>
          </div>
        </div>
      </div>

      <div class="row-5">
        <%= render 'categories', categories: @categories %>
      </div>

      <div class="row-6">
        <%= render 'bringing'%>
      </div>

  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<section id="footer">
  <div id="orange-line"> </div>
  <article class="container">
    <div id="footer-bio">
      <div id="mobile-menu-logo-item"> <%= image_tag('logo.png') %></div>
      <p>Audiophile is an all in one stop to fulfill your audio needs. We're a small team of music lovers
      and sound specialists who are devoted to helping you get the most out of personal audio. Come and
      visit our demo facility - we're open 7 days a week.</p>
    </div>
    <div id="footer-menu">
      <ul>
      <li> <%= link_to "Home", root_path %></li>
      <% @categories.each do |category|  %>
      <li><%= link_to category.name, category_path(category)%></li>
      <% end %>
      </ul>
    </div>
    <div id="footer-copyright">
    <p><strong>Copyright 2021. All rights reserved.</strong></p>
    </div>
    <div id="footer-social">
    <ul>
      <li> <a href="#"><%= cl_image_tag('audiophile/shared/desktop/icon-instagram_rz7ob9') %></a> </li>
      <li> <a href="#"><%= cl_image_tag('audiophile/shared/desktop/icon-twitter_sm6gss') %></a> </li>
      <li> <a href="#"><%= cl_image_tag('audiophile/shared/desktop/icon-facebook_pmepnm') %></a> </li>
    </ul>
    </div>
  </article>
</section>

app/views/shared/_navbar.html.erb
<section id="mobilenav">
<div id="close-mobile"> X </div>
  <div class="container">
    <div id="mobile-menu-pages-item">
      <div> <%= link_to "Home", root_path %></div>
      <% @categories.each do |category|  %>
      <div><%= link_to category.name, category_path(category)%></div>
      <% end %>
    </div>
  </div>
   <div id="mobile-menu-logo-item"> <%= image_tag('logo.png') %></div>
</section>

<section id="navbar">
    <div class="container">
      <div id="menu-mobile">
        <div></div>
        <div></div>
        <div></div>
      </div>
      <div id="menu-logo-item"> <%= image_tag('logo.png') %></div>
        <div id="menu-pages-item">
          <div> <%= link_to "Home", root_path %></div>
          <% @categories.each do |category|  %>
            <div><%= link_to category.name, category_path(category)%></div>
          <% end %>
        </div>
      <div id="menu-cart-item"> <%= link_to image_tag('icon-cart.png'), current_user ? cart_path(current_user) : new_user_session_path  %> </div>
    </div>
</section>